products:
  # - name: EDB JDBC Connector
  #   platforms:
  #     - name: CentOS 7
  #       arch: x86_64
  #       supported versions: [42.x.x]
  #     - name: CentOS 7
  #       arch: ppc64le
  #       supported versions: [42.x.x]
  #     - name: AlmaLinux 8 or Rocky Linux 8
  #       arch: x86_64
  #       supported versions: [42.x.x]
  #     - name: RHEL 7 or OL 7 
  #       arch: x86_64
  #       supported versions: [42.x.x]
  #     - name: RHEL 7 or OL 7
  #       arch: ppc64le
  #       supported versions: [42.x.x]
  #     - name: RHEL 8 or OL 8
  #       arch: x86_64
  #       supported versions: [42.x.x]
  #     - name: Ubuntu 18.04 or Debian 9
  #       arch: x86_64
  #       supported versions: [42.x.x]
  #     - name: Ubuntu 20.04 or Debian 10
  #       arch: x86_64
  #       supported versions: [42.x.x]
      # - name: SLES 12
      #   arch: x86_64
      #   supported versions: [42.x.x]
      # - name: SLES 12
      #   arch: ppc64le
      #   supported versions: [42.x.x]
      # - name: SLES 15
      #   arch: x86_64
      #   supported versions: [42.x.x]
      # - name: SLES 15
      #   arch: ppc64le
      #   supported versions: [42.x.x]
  # - name: Migration Toolkit
  #   platforms:
#      - name: RHEL 8 or OL 8
#        arch: x86_64
#        supported versions: [55]
#      - name: AlmaLinux 8 or Rocky Linux 8
#        arch: x86_64
#        supported versions: [55]
#      - name: RHEL 7 or OL 7
#        arch: x86_64
#        supported versions: [55]
#      - name: CentOS 7
#        arch: x86_64
#        supported versions: [55]
      # - name: SLES 15
      #   arch: x86_64
      #   supported versions: [55]
      # - name: SLES 12
      #   arch: ppc64le
      #   supported versions: [55]
#      - name: Ubuntu 20.04 or Debian 10
#        arch: x86_64
#        supported versions: [55]
#      - name: Ubuntu 18.04 or Debian 9
#        arch: x86_64
#        supported versions: [55]
#      - name: RHEL 8 or OL 8
#        arch: ppc64le
#        supported versions: [55]
#      - name: RHEL 7 or OL 7
#        arch: ppc64le
#        supported versions: [55]
      # - name: SLES 15
      #   arch: ppc64le
      #   supported versions: [55]
      # - name: SLES 12
      #   arch: x86_64
      #   supported versions: [55]
  # - name: EDB OCI Connector
  #   platforms:
  #     - name: CentOS 7
  #       arch: x86_64
  #       supported versions: [14.1.0.1]
  #     - name: CentOS 7
  #       arch: ppc64le
  #       supported versions: [14.1.0.1]
  #     - name: AlmaLinux 8 or Rocky Linux 8
  #       arch: x86_64
  #       supported versions: [14.1.0.1]
  #     - name: RHEL 7 or OL 7 
  #       arch: x86_64
  #       supported versions: [14.1.0.1]
  #     - name: RHEL 7 or OL 7
  #       arch: ppc64le
  #       supported versions: [14.1.0.1]
  #     - name: RHEL 8 or OL 8
  #       arch: x86_64
  #       supported versions: [14.1.0.1]
  #     - name: Ubuntu 18.04 or Debian 9
  #       arch: x86_64
  #       supported versions: [14.1.0.1]
  #     - name: Ubuntu 20.04 or Debian 10
  #       arch: x86_64
  #       supported versions: [14.1.0.1]
      # - name: SLES 12
      #   arch: x86_64
      #   supported versions: [14.1.0.1]
      # - name: SLES 12
      #   arch: ppc64le
      #   supported versions: [14.1.0.1]
      # - name: SLES 15
      #   arch: x86_64
      #   supported versions: [14.1.0.1]
      # - name: SLES 15
      #   arch: ppc64le
      #   supported versions: [14.1.0.1]
  # - name: EDB ODBC Connector
  #   platforms:
  #     - name: CentOS 7
  #       arch: x86_64
  #       supported versions: [13.1.0.2]
  #     - name: CentOS 7
  #       arch: ppc64le
  #       supported versions: [13.1.0.2]
  #     - name: AlmaLinux 8 or Rocky Linux 8
  #       arch: x86_64
  #       supported versions: [13.1.0.2]
  #     - name: RHEL 7 or OL 7 
  #       arch: x86_64
  #       supported versions: [13.1.0.2]
  #     - name: RHEL 7 or OL 7
  #       arch: ppc64le
  #       supported versions: [13.1.0.2]
  #     - name: RHEL 8 or OL 8
  #       arch: x86_64
  #       supported versions: [13.1.0.2]
  #     - name: Ubuntu 18.04 or Debian 9
  #       arch: x86_64
  #       supported versions: [13.1.0.2]
  #     - name: Ubuntu 20.04 or Debian 10
  #       arch: x86_64
  #       supported versions: [13.1.0.2]
      # - name: SLES 12
      #   arch: x86_64
      #   supported versions: [13.1.0.2]
      # - name: SLES 12
      #   arch: ppc64le
      #   supported versions: [13.1.0.2]
      # - name: SLES 15
      #   arch: x86_64
      #   supported versions: [13.1.0.2]
      # - name: SLES 15
      #   arch: ppc64le
      #   supported versions: [13.1.0.2]
  # - name: EDB pgBouncer
  #   platforms:
  #     - name: CentOS 7
  #       arch: x86_64
  #       supported versions: [1.14, 1.15, 1.16]
  #     - name: CentOS 7
  #       arch: ppc64le
  #       supported versions: [1.14, 1.15, 1.16]
  #     - name: AlmaLinux 8 or Rocky Linux 8
  #       arch: x86_64
  #       supported versions: [1.14, 1.15, 1.16]
  #     - name: RHEL 7 or OL 7 
  #       arch: x86_64
  #       supported versions: [1.14, 1.15, 1.16]
  #     - name: RHEL 7 or OL 7
  #       arch: ppc64le
  #       supported versions: [1.14, 1.15, 1.16]
  #     - name: RHEL 8 or OL 8
  #       arch: x86_64
  #       supported versions: [1.14, 1.15, 1.16]
  #     - name: Ubuntu 18.04 or Debian 9
  #       arch: x86_64
  #       supported versions: [1.14, 1.15, 1.16]
  #     - name: Ubuntu 20.04 or Debian 10
  #       arch: x86_64
  #       supported versions: [1.14, 1.15, 1.16]
      # - name: SLES 12
      #   arch: x86_64
      #   supported versions: [1.16]
      # - name: SLES 12
      #   arch: ppc64le
      #   supported versions: [1.16]
      # - name: SLES 15
      #   arch: x86_64
      #   supported versions: [1.16]
      # - name: SLES 15
      #   arch: ppc64le
      #   supported versions: [1.16]
  # - name: EDB PgpoolII
  #   platforms:
  #     - name: CentOS 7
  #       arch: x86_64
  #       supported versions: [4.0, 4.1, 4.2, 4.3]
  #     - name: CentOS 7
  #       arch: ppc64le
  #       supported versions: [4.0, 4.1, 4.2, 4.3]
  #     - name: AlmaLinux 8 or Rocky Linux 8
  #       arch: x86_64
  #       supported versions: [4.0, 4.1, 4.2, 4.3]
  #     - name: RHEL 7 or OL 7 
  #       arch: x86_64
  #       supported versions: [4.0, 4.1, 4.2, 4.3]
  #     - name: RHEL 7 or OL 7
  #       arch: ppc64le
  #       supported versions: [4.0, 4.1, 4.2, 4.3]
  #     - name: RHEL 8 or OL 8
  #       arch: x86_64
  #       supported versions: [4.0, 4.1, 4.2, 4.3]
  #     - name: Ubuntu 18.04 or Debian 9
  #       arch: x86_64
  #       supported versions: [4.0, 4.1, 4.2, 4.3]
  #     - name: Ubuntu 20.04 or Debian 10
  #       arch: x86_64
  #       supported versions: [4.0, 4.1, 4.2, 4.3]
    #  - name: SLES 12
    #    arch: x86_64
    #    supported versions: [4.3]
    #  - name: SLES 12
    #    arch: ppc64le
    #    supported versions: [4.3]
    #  - name: SLES 15
    #    arch: x86_64
    #    supported versions: [4.3]
    #  - name: SLES 15
    #    arch: ppc64le
    #    supported versions: [4.3]
  # - name: EDB Postgres Advanced Server
  #   platforms:
  #     - name: CentOS 7
  #       arch: x86_64
  #       supported versions: [10, 11, 12, 13, 14]
  #     - name: CentOS 7
  #       arch: ppc64le
  #       supported versions: [10, 11, 12, 13, 14]
  #     - name: AlmaLinux 8 or Rocky Linux 8
  #       arch: x86_64
  #       supported versions: [11, 12, 13, 14]
  #     - name: RHEL 7 or OL 7 
  #       arch: x86_64
  #       supported versions: [9.6, 10, 11, 12, 13, 14]
  #     - name: RHEL 7 or OL 7
  #       arch: ppc64le
  #       supported versions: [9.6, 10, 11, 12, 13, 14]
  #     - name: RHEL 7 or OL 7
  #       arch: local
  #       supported versions: [9.6, 10, 11, 12, 13, 14]
  #     - name: RHEL 8 or OL 8
  #       arch: x86_64
  #       supported versions: [11, 12, 13, 14]
  #     - name: RHEL 8 or OL 8
  #       arch: Linux on IBM Power (ppc64le)
  #       supported versions: [11, 12, 13, 14]
  #     - name: Ubuntu 18.04 or Debian 9
  #       arch: x86_64
  #       supported versions: [11, 12, 13, 14]
  #     - name: Ubuntu 20.04 or Debian 10
  #       arch: x86_64
  #       supported versions: [13, 14]
    #  - name: SLES 12
    #    arch: x86_64
    #    supported versions: [14]
    #  - name: SLES 15
    #    arch: x86_64
    #    supported versions: [14]
    #  - name: SLES 12
    #    arch: ppc64le
    #    supported versions: [14]
    #  - name: SLES 15
    #    arch: ppc64le
    #    supported versions: [14]
  # - name: EDB*Plus
  #   platforms:
  #     - name: CentOS 7
  #       arch: x86_64
  #       supported versions: [9.6, 11, 12, 13, 14]
  #     - name: CentOS 7
  #       arch: ppc64le
  #       supported versions: [9.6, 11, 12, 13, 14]
  #     - name: AlmaLinux 8 or Rocky Linux 8
  #       arch: x86_64
  #       supported versions: [9.6, 11, 12, 13, 14]
  #     - name: RHEL 7 or OL 7 
  #       arch: x86_64
  #       supported versions: [9.6, 11, 12, 13, 14]
  #     - name: RHEL 7 or OL 7
  #       arch: ppc64le
  #       supported versions: [9.6, 11, 12, 13, 14]
  #     - name: RHEL 8 or OL 8
  #       arch: x86_64
  #       supported versions: [9.6, 11, 12, 13, 14]
  #     - name: Ubuntu 18.04 or Debian 9
  #       arch: x86_64
  #       supported versions: [9.6, 11, 12, 13, 14]
  #     - name: Ubuntu 20.04 or Debian 10
  #       arch: x86_64
  #       supported versions: [9.6, 11, 12, 13, 14]
      # - name: SLES 12
      #   arch: x86_64
      #   supported versions: [14]
      # - name: SLES 12
      #   arch: ppc64le
      #   supported versions: [14]
      # - name: SLES 15
      #   arch: x86_64
      #   supported versions: [14]
      # - name: SLES 15
      #   arch: ppc64le
      #   supported versions: [14]
  - name: Failover Manager
    platforms:
  #     - name: CentOS 7
  #       arch: x86_64
  #       supported versions: [3.10, 4.0, 4.1, 4.2, 4.3, 4.4]
  #     - name: CentOS 7
  #       arch: ppc64le
  #       supported versions: [3.10, 4.0, 4.1, 4.2, 4.3, 4.4]
  #     - name: AlmaLinux 8 or Rocky Linux 8
  #       arch: x86_64
  #       supported versions: [3.10, 4.0, 4.1, 4.2, 4.3, 4.4]
  #     - name: RHEL 7 or OL 7 
  #       arch: x86_64
  #       supported versions: [3.10, 4.0, 4.1, 4.2, 4.3, 4.4]
  #     - name: RHEL 7 or OL 7
  #       arch: ppc64le
  #       supported versions: [3.10, 4.0, 4.1, 4.2, 4.3, 4.4]
  #     - name: RHEL 8 or OL 8
  #       arch: x86_64
  #       supported versions: [3.10, 4.0, 4.1, 4.2, 4.3, 4.4]
  #     - name: Ubuntu 18.04 or Debian 9
  #       arch: x86_64
  #       supported versions: [3.10, 4.0, 4.1, 4.2, 4.3, 4.4]
  #     - name: Ubuntu 20.04 or Debian 10
  #       arch: x86_64
  #       supported versions: [3.10, 4.0, 4.1, 4.2, 4.3, 4.4]
      - name: SLES 12
        arch: x86_64
        supported versions: [4.4]
      - name: SLES 12
        arch: ppc64le
        supported versions: [4.4]
      - name: SLES 15
        arch: x86_64
        supported versions: [4.4]
      - name: SLES 15
        arch: ppc64le
        supported versions: [4.4]
  # - name: Hadoop Foreign Data Wrapper
  #   platforms:
  #     - name: CentOS 7
  #       arch: x86_64
  #       supported versions: [14]
  #     - name: CentOS 7
  #       arch: ppc64le
  #       supported versions: [14]
  #     - name: AlmaLinux 8 or Rocky Linux 8
  #       arch: x86_64
  #       supported versions: [14]
  #     - name: RHEL 7 or OL 7 
  #       arch: x86_64
  #       supported versions: [14]
  #     - name: RHEL 7 or OL 7
  #       arch: ppc64le
  #       supported versions: [14]
  #     - name: RHEL 8 or OL 8
  #       arch: x86_64
  #       supported versions: [14]
  #     - name: Ubuntu 18.04 or Debian 9
  #       arch: x86_64
  #       supported versions: [14]
  #     - name: Ubuntu 20.04 or Debian 10
  #       arch: x86_64
  #       supported versions: [14]
      # - name: SLES 12
      #   arch: x86_64
      #   supported versions: [14]
      # - name: SLES 12
      #   arch: ppc64le
      #   supported versions: [14]
      # - name: SLES 15
      #   arch: x86_64
      #   supported versions: [14]
      # - name: SLES 15
      #   arch: ppc64le
      #   supported versions: [14]
  # - name: MongoDB Foreign Data Wrapper
  #   platforms:
  #     - name: CentOS 7
  #       arch: x86_64
  #       supported versions: [11, 12, 13, 14]
  #     - name: CentOS 7
  #       arch: ppc64le
  #       supported versions: [11, 12, 13, 14]
  #     - name: AlmaLinux 8 or Rocky Linux 8
  #       arch: x86_64
  #       supported versions: [11, 12, 13, 14]
  #     - name: RHEL 7 or OL 7 
  #       arch: x86_64
  #       supported versions: [11, 12, 13, 14]
  #     - name: RHEL 7 or OL 7
  #       arch: ppc64le
  #       supported versions: [11, 12, 13, 14]
  #     - name: RHEL 8 or OL 8
  #       arch: x86_64
  #       supported versions: [11, 12, 13, 14]
  #     - name: Ubuntu 18.04 or Debian 9
  #       arch: x86_64
  #       supported versions: [11, 12, 13, 14]
  #     - name: Ubuntu 20.04 or Debian 10
  #       arch: x86_64
  #       supported versions: [11, 12, 13, 14]
      # - name: SLES 12
      #   arch: x86_64
      #   supported versions: [14]
      # - name: SLES 12
      #   arch: ppc64le
      #   supported versions: [14]
      # - name: SLES 15
      #   arch: x86_64
      #   supported versions: [14]
      # - name: SLES 15
      #   arch: ppc64le
      #   supported versions: [14]
  # - name: MySQL Foreign Data Wrapper
  #   platforms:
  #     - name: CentOS 7
  #       arch: x86_64
  #       supported versions: [11, 12, 13, 14]
  #     - name: CentOS 7
  #       arch: ppc64le
  #       supported versions: [11, 12, 13, 14]
  #     - name: AlmaLinux 8 or Rocky Linux 8
  #       arch: x86_64
  #       supported versions: [11, 12, 13, 14]
  #     - name: RHEL 7 or OL 7 
  #       arch: x86_64
  #       supported versions: [11, 12, 13, 14]
  #     - name: RHEL 7 or OL 7
  #       arch: ppc64le
  #       supported versions: [11, 12, 13, 14]
  #     - name: RHEL 8 or OL 8
  #       arch: x86_64
  #       supported versions: [11, 12, 13, 14]
  #     - name: Ubuntu 18.04 or Debian 9
  #       arch: x86_64
  #       supported versions: [11, 12, 13, 14]
  #     - name: Ubuntu 20.04 or Debian 10
  #       arch: x86_64
  #       supported versions: [11, 12, 13, 14]
      # - name: SLES 12
      #   arch: x86_64
      #   supported versions: [14]
      # - name: SLES 12
      #   arch: ppc64le
      #   supported versions: [14]
      # - name: SLES 15
      #   arch: x86_64
      #   supported versions: [14]
      # - name: SLES 15
      #   arch: ppc64le
      #   supported versions: [14]
  # - name: PostGIS
  #   platforms:
  #     - name: CentOS 7
  #       arch: x86_64
  #       supported versions: [11, 12, 13, 14]
  #     - name: CentOS 7
  #       arch: ppc64le
  #       supported versions: [11, 12, 13, 14]
  #     - name: AlmaLinux 8 or Rocky Linux 8
  #       arch: x86_64
  #       supported versions: [11, 12, 13, 14]
  #     - name: RHEL 7 or OL 7 
  #       arch: x86_64
  #       supported versions: [11, 12, 13, 14]
  #     - name: RHEL 7 or OL 7
  #       arch: ppc64le
  #       supported versions: [11, 12, 13, 14]
  #     - name: RHEL 8 or OL 8
  #       arch: x86_64
  #       supported versions: [11, 12, 13, 14]
  #     - name: Ubuntu 18.04 or Debian 9
  #       arch: x86_64
  #       supported versions: [11, 12, 13, 14]
  #     - name: Ubuntu 20.04 or Debian 10
  #       arch: x86_64
  #       supported versions: [11, 12, 13, 14]
      # - name: SLES 12
      #   arch: x86_64
      #   supported versions: [14]
      # - name: SLES 12
      #   arch: ppc64le
      #   supported versions: [14]
      # - name: SLES 15
      #   arch: x86_64
      #   supported versions: [14]
      # - name: SLES 15
      #   arch: ppc64le
      #   supported versions: [14]
  # - name: Postgres Enterprise Manager
  #   platforms:
  #     - name: CentOS 7
  #       arch: x86_64
  #       supported versions: [7, 8]
  #     - name: CentOS 7
  #       arch: ppc64le
  #       supported versions: [7, 8]
  #     - name: AlmaLinux 8 or Rocky Linux 8
  #       arch: x86_64
  #       supported versions: [7, 8]
  #     - name: RHEL 7 or OL 7 
  #       arch: x86_64
  #       supported versions: [7, 8]
  #     - name: RHEL 7 or OL 7
  #       arch: ppc64le
  #       supported versions: [7, 8]
  #     - name: RHEL 8 or OL 8
  #       arch: x86_64
  #       supported versions: [7, 8]
  #     - name: Ubuntu 18.04 or Debian 9
  #       arch: x86_64
  #       supported versions: [7, 8]
  #     - name: Ubuntu 20.04 or Debian 10
  #       arch: x86_64
  #       supported versions: [7, 8]
      # - name: SLES 12
      #   arch: x86_64
      #   supported versions: [8]
      # - name: SLES 15
      #   arch: x86_64
      #   supported versions: [8]
      # - name: SLES 12
      #   arch: ppc64le
      #   supported versions: [8]
      # - name: SLES 15
      #   arch: ppc64le
      #   supported versions: [8]




