products:
  - name: EDB Postgres Advanced Server
    platforms:
      - name: CentOS 7
        arch: x86_64
        supported versions: [9.6, 10, 11, 12, 13, 14]
      - name: CentOS 7
        arch: ppc64le
        supported versions: [9.6, 10, 11, 12, 13, 14]
      - name: CentOS 8
        arch: x86_64
        supported versions: [11, 12, 13, 14]
      - name: RHEL 7
        arch: x86_64
        supported versions: [9.6, 10, 11, 12, 13, 14]
      - name: RHEL 7
        arch: ppc64le
        supported versions: [9.6, 10, 11, 12, 13, 14]
      - name: RHEL 8
        arch: x86_64
        supported versions: [11, 12, 13, 14]
      - name: Debian 9
        arch: x86_64
        supported versions: [11, 12, 13, 14]
      - name: Debian 10
        arch: x86_64
        supported versions: [12, 13, 14]
      - name: Ubuntu 18.04
        arch: x86_64
        supported versions: [11, 12, 13, 14]
      - name: Ubuntu 20.04
        arch: x86_64
        supported versions: [13, 14]
      - name: SLES 12
        arch: x86_64
        supported versions: [9.6, 11, 12]
