version: '3.8'

services:
  pdf-builder:
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.pdf-builder
    image: edb/x-docs-pdf-builder
    container_name: pdf-builder
    hostname: pdf-builder
    working_dir: /app
    volumes:
      - ../:/app
