version: "3.8"

services:
  install-docs-template-renderer:
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.install-template
    image: edb/docs-install-template
    container_name: docs-install-template
    hostname: docs-install-template
<<<<<<< HEAD
    command: sh -c "npm i && node main.mjs"
    volumes:
      - ../install_template/config.yaml:/app/config.yaml:ro
      - ../install_template/main.mjs:/app/main.mjs:ro
      - ../install_template/package-lock.json:/app/package-lock.json
      - ../install_template/package.json:/app/package.json
      - ../install_template/templates:/app/templates:ro
      - ../install_template/renders:/app/renders
=======
    volumes:
      - ../:/app/docs
      - ../install_template/templates:/app/templates:ro
      - ../install_template/config.yaml:/app/config.yaml:ro
      - ../install_template/renders:/app/renders
    command: node main.mjs
>>>>>>> 9015d7c09... dockerize template rendering process
