name: sync files from another repo
on:
  repository_dispatch:
    types: [sync_files]
jobs:
  sync-files:
    env:
      # The body text of the PR requests that will be created
      PR_BODY: Automated changes to pull in updates from ${{ github.event.client_payload.repo }} repo

      # The name of the branch that will be created
      PR_BRANCH_NAME: ${{ github.workflow }}/${{ github.event.client_payload.repo }}

      # The title of the PR request that will be created
      PR_TITLE: Automated changes from ${{ github.event.client_payload.repo }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout destination
        uses: actions/checkout@v2
        with:
          path: destination

      - name: Checkout source repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.repo }}
          token: ${{ secrets.GH_TOKEN }}
          path: source

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Process changes
        run: |
          case ${{ github.event.client_payload.repo }} in

            jaek-s/cloud-native-postgresql)
              cd ${{ github.workspace }}/destination/scripts/fileProcessor
              npm install production

              cd ${{ github.workspace }}/source/docs

              node ${{ github.workspace }}/destination/scripts/fileProcessor/main.mjs \
                -f "src/**/quickstart.md" \
                -p cnp/add-quickstart-content

              node ${{ github.workspace }}/destination/scripts/fileProcessor/main.mjs \
                -f "src/**/*.md" \
                -p "cnp/update-yaml-links" \
                -p "cnp/add-frontmatters" \
                -p "cnp/rename-to-mdx"

              cp -f src/* ${{ github.workspace }}/destination/advocacy_docs/kubernetes/
              ;;

            EnterpriseDB/fe)
              cp -f utils/icons-placeholder/output/* ${{ github.workspace }}/destination/icons-pkg/
              ;;

            *)
              echo "The workflow has not been configured for the  ${{ github.event.client_payload.repo }} repo"
              exit 1
              ;;
          esac
        working-directory: source

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          body: ${{ env.PR_BODY }}
          branch: ${{ env.PR_BRANCH_NAME }}
          path: destination/
          title: ${{ env.PR_TITLE }}
