name: Update PDFs on Develop
on:
  push:
    branches:
    - develop
    paths:
    - product_docs/docs/**.mdx
    - scripts/pdf/generate_pdf.py
jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        ref: develop
        ssh-key:  ${{ secrets.ADMIN_SECRET_SSH_KEY }}
    - name: Update submodules
      run: git submodule update --init --remote

    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - uses: r-lib/actions/setup-pandoc@v1
      with:
        pandoc-version: '2.10.1'
    - name: Install wkhtmltopdf
      run: |
        curl -L https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb > wkhtmltopdf.deb
        sudo apt-get install ./wkhtmltopdf.deb

    - name: Build all pdfs
      run: npm run build-all-pdfs

    - run: git status
    - run: git pull
    - name: Commit pdfs to develop
      run: |
        git config user.name josh-heyer
        git config user.email josh.heyer@enterprisedb.com
        git add *.pdf
        git commit -m "New PDFs generated by Github Actions"
        git push
